### ISSUE TITLE
shacl2ShEx/shaclConvert Not Working

### ISSUE THREAD

**Issue by init-dcat-ap-de** [weso/rdfshape-api#132]
Hello,
tried with Firefox and Chrome, but:

- All "Data format" drop downs are empty
- I can't paste or write in "by Input" text boxes

(And shouldn't there be a "Visualize SHACL schema" option?)

Thank you for your work!

**Comment by thewilly** [comment]
Yes, we are having some issues with the server where the application is located, we will try to solve it ASAP.

Thanks four your report!! ❤️

**Comment by labra** [comment]
Thanks for the report. You can try it again and I think it works again as expected.

**Comment by init-dcat-ap-de** [comment]
Hi, the dropdowns have data but the text boxes are without dunction and converting doesn't start.
Do I have to convert SHACL to ShEx to use the visualization online?

**Comment by labra** [comment]
Sorry for the delay in answering. In principle, the goal is that it also works and visualized SHACL shapes, but the SHACL 2 UML visualization is not finished yet as described [here](https://github.com/weso/umlShaclex/issues/4). If you are planning to use it in the near future we could give it more priority. 

Thanks for using the tool. We really appreciate your input.

**Comment by init-dcat-ap-de** [comment]
Whether or not we are going to use the service depends on the results we get from it... 
So don't do it for me, but do it anyways? :-)

**Comment by ulitol97** [comment]
Shacl 2 ShEx has been working for a long time now. If problems arise using it, new issues may be opened.
Additionally, the input/output formats of the conversion tools have been made more clear.

Closing this issue.
