### ISSUE TITLE
Show RDF data and ShEx/SHACL/SPARQL in parallel

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-api#192]
When using a desktop computer with a wide screen it would be nice to be able to see the RDF data pane and the ShEx/SHACL/SPARQL pane side by side in parallel.

**Comment by ulitol97** [comment]
I agree, a UI overhaul is needed for some scenarios. For now, and to avoid redundancy, I'm closing this issue so that we can discuss this in #33.
