### ISSUE TITLE
Analyze why the rdfshape-api is going down from time to time... 

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-api#275]
At this moment the rdfshape-API is crashing from time to time...one hypothesis is that the logs are very big and it decreases the performance...check if that's the reason and what actions we could take to palliate it.

**Comment by ulitol97** [comment]
Several measures have been taken to prevent this behaviour since the issue arose:

- Logs are rotated, compressed and limited in size
- Dependency versions have been updated with their corresponding bug fixes
- A new monitoring system that re-launches unresponsive containers in our deployment setup
