### ISSUE TITLE
Refactor the Javascript code

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-api#29]
At this moment, the Javascript code in RDFShape is a bit hidden in the folder [`modules/server/src/main/resources/staticviews`](https://github.com/labra/rdfshape/tree/master/modules/server/src/main/resources/staticviews) and it has been evolving from a small set of scripts to something that contains more logic about results visualization. 

It would be better to refactor that code using ES6, Typescript or even ScalaJS.

**Comment by ulitol97** [comment]
Outdated, we are maintaining JS clients in separated repos now.
