### ISSUE TITLE
Add API option to validate through wikibaserdf using SPARQL queries

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-api#90]

**Comment by ulitol97** [comment]
The API endpoint [/wikibase/validate](https://app.swaggerhub.com/apis-docs/weso/RDFShape/0.2.4#operations-wikibase-postWikibaseValidate-body) already allows users to validate SPARQL query results against a given schema and can be used in a friendly manner in [Wikishape](https://wikishape.weso.es/validateSparql).

Example: https://wikishape.weso.es/link/16474240769
